apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music-local-pvc
  namespace: navidrome
  labels:
    app: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
