# NFS PersistentVolume for music files from Arch VM
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music-pv
  labels:
    app: navidrome
    type: nfs-music
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.68.105
    path: /home/onion/Music
    readOnly: true
  mountOptions:
    - nfsvers=4
    - ro
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music-pvc
  namespace: navidrome
  labels:
    app: navidrome
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: nfs-music
  storageClassName: ""
  volumeName: navidrome-music-pv
